### ISSUE TITLE
URL is not working

### ISSUE THREAD

**Issue by johnisaway285** [ZigaoWang/dazcalc#3]
Hello, Zigao, your URL is not working. When I clicked that link, it said 404.

**Comment by ZigaoWang** [comment]
Hello! Thank you for bringing the issue to my attention. I want to inform you that I've recently updated my domain, which resulted in some changes to the URLs for my projects, including DazCalc. Fortunately, I've taken the necessary steps to resolve this issue, and everything should be working smoothly now. However, if you encounter any lingering problems or have any further questions, please don't hesitate to reach out to me. Your feedback is greatly appreciated!
